use anyhow::{Result, anyhow};
use serde::{Deserialize, Serialize};

/// One element of the MCP `tools/call` response's `content` array. The Figma
/// MCP returns a `Vec<ContentBlock>` per call; block[0] holds the TSX code
/// and the rest are human-readable notes (conversion guidance, styles digest,
/// asset TTL note, etc.).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContentBlock {
    #[serde(rename = "type")]
    pub block_type: String,
    #[serde(default)]
    pub text: String,
}

pub struct Extracted {
    pub code: String,
    pub styles_digest: Option<String>,
}

/// Pull the TSX code block out of the get_design_context response, plus any auxiliary
/// metadata blocks we want to surface in the output header.
///
/// The server returns ~5 text blocks; only block[0] (the code) is required.
/// Other blocks contain conversion guidance, a styles digest, and asset notes.
pub fn extract(blocks: &[ContentBlock]) -> Result<Extracted> {
    let mut code: Option<String> = None;
    let mut styles_digest: Option<String> = None;

    for b in blocks {
        if b.block_type != "text" {
            continue;
        }
        let t = b.text.trim_start();
        if code.is_none() && is_code(t) {
            code = Some(b.text.clone());
        } else if t.starts_with("These styles") {
            styles_digest = Some(b.text.clone());
        }
    }

    let code = code.ok_or_else(|| {
        anyhow!(
            "response contained no code block.\n\
             The node may be a Figma `section` (the server returns metadata then \
             tells the caller to recurse into children). Re-run the MCP fetch on a \
             child frame's node id."
        )
    })?;

    Ok(Extracted {
        code,
        styles_digest,
    })
}

fn is_code(text: &str) -> bool {
    text.starts_with("const ")
        || text.starts_with("import ")
        || text.starts_with("export ")
        || text.starts_with("function ")
}

pub fn build_header(
    source_url: &str,
    file_key: &str,
    node_id: &str,
    styles_digest: Option<&str>,
) -> String {
    let mut h = String::new();
    h.push_str("// Auto-generated by figma-code-dl\n");
    h.push_str(&format!("// Source: {source_url}\n"));
    h.push_str(&format!("// file={file_key} node={node_id}\n"));
    h.push_str(
        "// NOTE: image URLs (api/mcp/asset/...) are temporary (7-day TTL). \
         Use --download-assets to copy them locally before relying on this file.\n",
    );
    if let Some(styles) = styles_digest {
        h.push_str("//\n// Styles digest (from get_design_context):\n");
        for line in styles.lines() {
            h.push_str("//   ");
            h.push_str(line);
            h.push('\n');
        }
    }
    h.push('\n');
    h
}

#[cfg(test)]
mod tests {
    use super::*;

    fn block(text: &str) -> ContentBlock {
        ContentBlock {
            block_type: "text".into(),
            text: text.into(),
        }
    }

    #[test]
    fn extracts_code_block_among_metadata() {
        let blocks = vec![
            block("const imgFoo = \"https://x\";\nexport default function Foo() {}"),
            block("SUPER CRITICAL: convert to target stack"),
            block("Node ids have been added"),
            block("These styles are contained in the design: Foo: Font(...)"),
            block("Images and SVGs will be stored as constants"),
        ];
        let e = extract(&blocks).unwrap();
        assert!(e.code.starts_with("const imgFoo"));
        assert!(
            e.styles_digest
                .as_ref()
                .unwrap()
                .starts_with("These styles")
        );
    }

    #[test]
    fn errors_when_no_code_block() {
        let blocks = vec![block("<section id=\"1:2\">...</section>")];
        assert!(extract(&blocks).is_err());
    }
}
